[project]
name = "norgeitall"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "polars>=1.24.0",
    "pre-commit>=4.1.0",
    "ruff>=0.9.9",
]
