name: continuous integration
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Test
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - run: uv run pre-commit run --all-files
      - run: uv run main.py
      - run: npm install
      - run: npm run sources
      - run: npm run build:strict
